# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shao Lab @ University of Macau
email: nshao@shaolab.eu.org
description: > # this means to ignore newlines until "baseurl:"
  A personal blog of myself, Ning-Yi SHAO, a postdoc of Stanford University
  School of Medicine, focusing on the things I feel interesting, mostly about
  bioinformatics, evolution, and medicine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shaolab.eu.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sny_cn
github_username:  ny-shao

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: nyshaogithub

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
